# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4eb9e4e63673b9587b6468033159bd9414752a0ba33aaff85af6e1f3b32a769f241516df0fc3263c9da5234866743adbdc4f85fe3a89d8e7b4472f19c1f66bb0

test:
  secret_key_base: c58368f50aa6fc9dbbe047e06a6205fa276c89aa98f3d92120f8f02181310bc082ecbdee56cc4fea07a2d1ba34ef9a183fbbfb5f7ba933685befe89c59a4c6ee

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
